### ISSUE TITLE
Create UsaMap view

### ISSUE THREAD

**Issue by Master-Foo** [Cabal-Syndicate/randora_server#16]
This is the widget we started working on yesterday.

Finish it and commit.

**Comment by Master-Foo** [comment]
When you commit, use the message " Create UsaMap view #16 " (The name of this issue)

``` bash
git commit -m " Create UsaMap view #16"
```

**Comment by Master-Foo** [comment]
FYI, you should only need to change that one file: /source/home/views/widgets/usa_map.d

**Comment by Master-Foo** [comment]
Be sure to pull from Cabal-Syndicate/randora_server before starting because I just made some changes that are relevant to this issue and you will need the latest version.

**Comment by Master-Foo** [comment]
Also, when you start an issue, leave a comment so I know what is being worked on.

**Comment by techwulf** [comment]
I have completed the map widget conversion to D language. The server runs without errors, but the widget doesn't show up on the webpage.

**Comment by Master-Foo** [comment]
I'll take a look at it now

**Comment by techwulf** [comment]
It is working now, but the map isn't showing. I pushed it to my repository.

**Comment by Master-Foo** [comment]
I'll take a look at it.

**Comment by Master-Foo** [comment]
It compiled fine on my machine. I can see the place where it is supposed to be. So, I think everything you did was good.

I'll take a closer look tomorrow. The problem is likely:
1 Firefox doesn't like the html being rendered. (view source in Firefox the red lines are code Firefox doesn't like)
2 The Javascript isn't correct.

Neither of these things are a fault of your code. Firefox is just being a prick. I know how to fix it, but I'll do it later.

Anyway, push to Cabal-Syndicate. Mission Accomplished!
