### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by techwulf** [Cabal-Syndicate/randora_server#3]
Hey

**Comment by Master-Foo** [comment]
Let's figure out what you are interested in working on.

First things first. Fork this project and then clone it to your machine. Try to compile it like this.

``` bash
git clone git@github.com:techwulf/randora_server.git
cd randora_server
dub upgrade
dub run
```

This **should** build and run the project. If not we'll figure out what is going on.

When it is running, open a browser and go to http://localhost:8080 and you'll see the results.

After that, I'll start to assign you some tasks which you can complete in about 10 minutes each. If you want to work on something specifically, let me know. Otherwise, I really need someone to go through and replace images and such.

Let me know when you are ready.

**Comment by techwulf** [comment]
It upgraded alright, but when I attempt to run the server I get an error.

source/widget/controller.d(552,2): Error: } expected following members in class declaration at source/widget/controller.d(5,1)
dmd failed with exit code 1.

**Comment by Master-Foo** [comment]
I'll look into it.

**Comment by Master-Foo** [comment]
yep I'm getting the same thing. I probably uploaded without double checking last night. I'll have a fix probably in a few minutes...

**Comment by Master-Foo** [comment]
Yep, one of those classic stupid bugs. It's good to go now.

**Comment by techwulf** [comment]
This time I don't know if I did something wrong. I am still figuring out git. I got allot of Errors.

source/randora/engine/app/app.d(4,1): Error: class randora.engine.app.app.RNDApp!(App, App).RNDApp has forward references
source/randora/ui/app/app.d(4,32): Error: template instance randora.engine.app.app.RNDApp!(App, App) error instantiating
views/game/apps/app.d(4,13):        instantiated from here: UIApp!(App, App)
source/randora/engine/container/container.d(4,1): Error: class randora.engine.container.container.RNDContainer!(App, App).RNDContainer has forward references
source/randora/engine/app/app.d(4,33): Error: template instance randora.engine.container.container.RNDContainer!(App, App) error instantiating
source/randora/ui/app/app.d(4,32):        instantiated from here: RNDApp!(App, App)
views/game/apps/app.d(4,13):        instantiated from here: UIApp!(App, App)
source/randora/engine/widget/widget.d(4,1): Error: class randora.engine.widget.widget.RNDWidget!(App).RNDWidget has forward references
source/randora/engine/container/container.d(4,42): Error: template instance randora.engine.widget.widget.RNDWidget!(App) error instantiating
source/randora/engine/app/app.d(4,33):        instantiated from here: RNDContainer!(App, App)
source/randora/ui/app/app.d(4,32):        instantiated from here: RNDApp!(App, App)
views/game/apps/app.d(4,13):        instantiated from here: UIApp!(App, App)
source/randora/engine/box/box/box_base.d(4,1): Error: class randora.engine.box.box.box_base.RNDBoxBase!(App).RNDBoxBase has forward references
source/randora/engine/box/box/box.d(4,24): Error: template instance randora.engine.box.box.box_base.RNDBoxBase!(App) error instantiating
source/randora/engine/widget/widget.d(4,27):        instantiated from here: RNDBox!(App)
source/randora/engine/container/container.d(4,42):        instantiated from here: RNDWidget!(App)
source/randora/engine/app/app.d(4,33):        instantiated from here: RNDContainer!(App, App)
source/randora/ui/app/app.d(4,32):        instantiated from here: RNDApp!(App, App)
views/game/apps/app.d(4,13):        instantiated from here: UIApp!(App, App)
source/randora/engine/box/box/box_base.d(4,28): Error: template instance randora.engine.owned.owned.RNDOwned!(App) error instantiating
source/randora/engine/box/box/box.d(4,24):        instantiated from here: RNDBoxBase!(App)
source/randora/engine/widget/widget.d(4,27):        instantiated from here: RNDBox!(App)
source/randora/engine/container/container.d(4,42):        instantiated from here: RNDWidget!(App)
source/randora/engine/app/app.d(4,33):        ... (1 instantiations, -v to show) ...
source/randora/ui/app/app.d(4,32):        instantiated from here: RNDApp!(App, App)
views/game/apps/app.d(4,13):        instantiated from here: UIApp!(App, App)
source/randora/engine/container/events/clean.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Clean!().on_clean does not override any function
source/randora/engine/container/container.d(7,2): Error: mixin randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Clean!() error instantiating
source/randora/engine/container/events/clear.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Clear!().on_clear does not override any function
source/randora/engine/container/container.d(8,2): Error: mixin randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Clear!() error instantiating
source/randora/engine/container/events/draw.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Draw!().on_draw does not override any function
source/randora/engine/container/container.d(9,2): Error: mixin randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Draw!() error instantiating
source/randora/engine/container/events/event.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Event!().on_event does not override any function
source/randora/engine/container/container.d(10,2): Error: mixin randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Event!() error instantiating
source/randora/engine/container/events/init.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Init!().on_init does not override any function
source/randora/engine/container/container.d(11,2): Error: mixin randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Init!() error instantiating
source/randora/engine/container/events/load.d(5,16): Error: function randora.engine.container.container.RNDContainer!(App, App).RNDContainer.Load!().on_load does not override any function
dmd failed with exit code 1.

**Comment by Master-Foo** [comment]
you are trying to compile randora_engine, not randora_server, which is a completely different project.

**Comment by techwulf** [comment]
Oh... whoops.

**Comment by Master-Foo** [comment]
email me your phone number or Skype and I'll walk you through everything.
